name: 03 - Workflow Runners

on: 
    push:

jobs:
    ubuntu-echo: 
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: echo "runs on ubuntu OS {{$RUNNER_OS}}" 