name: 03 - Workflow Runners

on: 
    workflow_dispatch:

jobs:
    ubuntu-echo: 
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: echo "runs on ubuntu OS {{$RUNNER_OS}}" 

    windows-echo:
        runs-on: windows-latest
        steps:
            - name: Show OS
              shell: bash
              run: echo "I runs on bash in windows {{$RUNNER_OS}}"

    mac-echo:
        runs-on: macos-latest
        steps:
            - name: Show OS
              run: echo "I run on MaC OS {{$RUNNER_OS}}"        